---
title: "In-class_Ex01"
author: "Wang Anqi"
execute:
  warning: false
---

# 1 Getting Started

## **1.1 Installing and loading the packages**

```{r}
pacman::p_load(tidyverse, jsonlite, 
               SmartEDA, tidygraph,
               ggraph)
```

## **1.2 Data import**

```{r}
kg <- fromJSON("data/MC1_graph.json")
```

## 1.3 Inspect structure

```{r}
str(kg, max.level = 1)
```

# 2 Extract and inspect

```{r}
nodes_tb1 <- as_tibble(kg$nodes)
edges_tb1 <- as_tibble(kg$links)
```

## 2.1 Initial EDA

```{r}
ggplot(data = edges_tb1,
       aes(y = `Edge Type`)) +
  geom_bar()
```

Step 1: Mapping from node id to row index

```{r}
id_map <- tibble(id = nodes_tb1$id,
                 index = seq_len(
                   nrow(nodes_tb1)
                 ))
```

This ensures each id from your node list is mapped to the correct row number.

Step 2 : Map source and target IDs to row

```{r}
edges_tb1 <- edges_tb1 %>%
  left_join(id_map, by = c("source" = "id")) %>%
  rename(from = index) %>%
  left_join(id_map, by = c("target" = "id")) %>%
  rename(to = index)

```

```{r}
edges_tb1 <- edges_tb1 %>%
  filter(!is.na(from), !is.na(to))
```

```{r}
graph <- tbl_graph(nodes = nodes_tb1,
                   edges = edges_tb1,
                   directed = kg$directed)
```

```{r}
set.seed(1234)
```

Visualising the whole Graph

```{r}
#| eval: false
ggraph(graph, layout = "fr") +
  geom_edge_link(alpha = 0.3,
                 colour = "gray") + 
  geom_node_point(aes(colour = `Node Type`),
                 size = 4) +
  geom_node_text(aes(label = name),
                 repel =  TRUE,
                 size = 2.5) +
  theme_void()
```

```{r}
graph_memberof <- graph %>%
  activate(edges) %>%
  filter(`Edge Type` == "Memberof")
```

```{r}
used_node_indices <- graph_memberof %>%
  activate(edges) %>%
  as_tibble() %>%
  select(from, to) %>%
  unlist() %>%
  unique()
```

Step 3 : Keep only those nodes

```{r}
graph_memberof <- graph_memberof %>%
  activate(nodes) %>%
  mutate(row_id = row_number()) %>%
  filter(row_id %in% used_node_indices) %>%
  select(-row_id) #optional cleanup
```

Plot the sub-graph
